#!/bin/bash
#
# A small wrapper to allow me to work with AWS assumed roles
#
SESSION_NAME=$(whoami)-$(date +%d-%m-%y_%H-%M)
ROLE_ARN=$(awk '/role_arn/ {print $3}' ~/.aws/config)
MFA_ARN=$(awk '/mfa_serial/ {print $3}' ~/.aws/config)

if [[ ! $MFA_TOKEN ]]; then
  echo "Error: must provide token"
  echo "MFA_TOKEN=token $0"
  exit 1
fi

unset AWS_SESSION_TOKEN

CREDENTIALS=$(aws sts assume-role \
                --role-session-name $SESSION_NAME \
                --role-arn $ROLE_ARN \
                --serial-number $MFA_ARN \
                --token-code $MFA_TOKEN)

if [[ $? == 0 ]]; then
  echo "export AWS_ACCESS_KEY_ID=$(echo ${CREDENTIALS} | jq -r '.Credentials | .AccessKeyId')"
  echo "export AWS_SECRET_ACCESS_KEY=$(echo ${CREDENTIALS} | jq -r '.Credentials | .SecretAccessKey')"
  echo "export AWS_SESSION_TOKEN=$(echo ${CREDENTIALS} | jq -r '.Credentials | .SessionToken')"
fi
