#!/bin/bash

VERSION=$1

if [[ -z $VERSION ]]; then
  echo "Usage: $0 update [version]"
  exit 1
fi

TMPFILE=$(mktemp)

wget "https://github.com/cli/cli/releases/download/v${VERSION}/gh_${VERSION}_linux_amd64.deb" -O "${TMPFILE}"
sudo dpkg -i "${TMPFILE}"
rm "${TMPFILE}"
