#!/bin/bash
set -e

SEARCH_WORD=$1
BRANCH_NAMES=$(git for-each-ref refs/heads --format='%(refname)' --sort='committerdate' |cut -d'/' -f3)
[[ -n "$SEARCH_WORD" ]] && BRANCH_NAMES=$(echo "$BRANCH_NAMES" |grep "$SEARCH_WORD")

# I tried various ways to split the string and then got fed up with bash, so
# doing it the easy way
BRANCH_COUNTER=0
for branch in $BRANCH_NAMES; do BRANCH_COUNTER=$(( BRANCH_COUNTER + 1 )); done

if [[ $BRANCH_COUNTER -eq 0 ]]; then exit; fi
if [[ $BRANCH_COUNTER -eq 1 ]]; then
  git switch "$BRANCH_NAMES"
  exit
fi

count=0
echo -e "ID\tBranch (Age)"
echo -e "--\t------------"

for branch in $BRANCH_NAMES; do
  echo -e "${count}\t${branch} ($(git log --pretty=format:'%cr' "${branch}" -n 1))"
  count=$(( count + 1 ))
done

read -p "Select branch: " -r answer
echo

count=0
for branch in $BRANCH_NAMES; do
  if [[ "$count" == "$answer" ]]; then
    git switch "$branch"
    exit
  fi
  count=$(( count + 1 ))
done

echo "Unable to switch branch"
exit 1
