#!/bin/bash
set -eo pipefail

main() {
  local delete=false
  local branch_name=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -d) delete=true ;;
      *)  branch_name="$1" ;;
    esac
    shift
  done

  if [[ -z "${branch_name}" ]]; then
    echo "Must provide branch name as argument"
    exit 1
  fi

  if [[ "${delete}" == true ]]; then
    local tree_path
    tree_path=$(proper_tree_path_name "${branch_name}")

    if [[ -z "${tree_path}" ]]; then
      echo "Worktree for ${branch_name} doesn't exist?"
      exit 1
    fi

    echo "Deleting ${tree_path}"
    git worktree remove "${tree_path}"
    exit
  fi

  local new_tree_path_name="$(basename "${PWD}")@${branch_name}"

  if git show-ref --verify --quiet "refs/heads/${branch_name}"; then
    git worktree add "../${new_tree_path_name}" "${branch_name}" >/dev/null
  else
    git worktree add -b "${branch_name}" "../${new_tree_path_name}" >/dev/null
  fi

  local tree_path
  tree_path=$(proper_tree_path_name "${branch_name}")

  if [[ -z "${tree_path}" ]]; then
    echo "Failed to find worktree after creation"
    exit 1
  fi

  echo "cd '${tree_path}'"
}

proper_tree_path_name() {
  git worktree list | grep -F "[$1]" | awk '{print $1}'
}

main "$@"
