#!/bin/bash
#
# gkit
#
# gitkit: doing stuff in git repos outside of git itself

####### usage
function usage() {
  cat <<EOF
gkit
====

  $0 <command>

Commands
========

  root: Change directory to root of the repository
  name: Print the name of the repository
EOF
}

####### helper functions
COMMAND=$1

function is_git_repo() {
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    true
  else
    echo "Not a git repository"
    exit 1
  fi
}

####### in-repo command functions

# change directory to the root of the repo
function root() {
  if is_git_repo; then
    cd $(git rev-parse --show-toplevel)
  fi
}

# print the name of the git repo
function name() {
  if is_git_repo; then
    basename -s .git `git config --get remote.origin.url`
  fi
}

###### run

if [[ -z $COMMAND ]]; then
  usage
  exit 1
fi

case $COMMAND in
  name) name;;
  root) root;;
  *) usage;;
esac
