#!/bin/bash
#
# I've had lots of networking issues recently and it's not always immediately
# clear when this occurs. I want to be notified so I can understand the
# situations when it's happening.
#
FAILURE_MEASURE=5

FAIL_COUNT=0

DOWN=false

while true; do
  if [[ $FAIL_COUNT -gt $FAILURE_MEASURE ]]; then
    if [[ $DOWN != "true" ]]; then
      echo "$(date): Network down" | tee -a /var/log/network-check.log
      DOWN=true
    fi
  fi

  if ! ping -w5 -nc 1 1.1.1.1 >/dev/null; then
    FAIL_COUNT=$(( FAIL_COUNT + 1 ))
  else
    # Reset the fail count
    if [[ $FAIL_COUNT -gt 0 ]]; then
      echo "$(date): Network stable" | tee -a /var/log/network-check.log
      FAIL_COUNT=0
    fi

    DOWN=false
  fi

  sleep 5
done
