#!/bin/bash

CMD=$1
NAME=$2

function name() {
  if [[ -z $NAME ]]; then
    echo "Must pick configured connection."
    echo -e "Options are:\n"
    nmcli con |grep vpn |awk '{print $1}'
    exit 1
  fi

  if ! nmcli con |grep -q $NAME; then
    echo "Cannot find VPN configured called \"${NAME}\""
    echo "Please set this up before using!"
    exit 1
  fi

  echo $NAME
}

is_active() {
  status=$(nmcli con |grep $(name) | awk '{print $4}')

  if [[ $status != "--" ]]; then
    echo "$(name) already active"
    exit
  else
    false
  fi
}

function vpn_id() {
  nmcli con |grep $(name) | awk '{print $2}'
}

case $CMD in
  on|up)
    is_active || nmcli --ask con up uuid "$(vpn_id)"
    ;;

  off|down)
    is_active && nmcli con down uuid "$(vpn_id)"
    ;;

  status)
    if [[ -z ${NAME} ]]; then
      nmcli con |head -n1; nmcli con |grep vpn
      exit
    fi

    if is_active; then
      echo "on"
    else
      echo "off"
    fi
    ;;

  *)
    echo "Arguments must be on, up, off or down"
    exit 1
    ;;
esac
