#!/bin/bash

CMD=$1
NAME=$2

function name() {
  if [[ -z $NAME ]]; then
    echo "Must pick configured connection."
    echo -e "Options are:\n"
    nmcli con |grep vpn |awk '{print $1}'
    exit 1
  fi

  if ! nmcli con |grep -q $NAME; then
    echo "Cannot find VPN configured called \"${NAME}\""
    echo "Please set this up before using!"
    exit 1
  fi

  echo $NAME
}

function vpn_id() {
  nmcli con |grep $(name) | awk '{print $2}'
}

is_active() {
  if [[ -z $1 ]]; then
    conn_name=$(name)
  else
    conn_name=$1
  fi

  status=$(nmcli con |grep $conn_name | awk '{print $4}')

  if [[ $status != "--" ]]; then
    true
  else
    false
  fi
}

function turn_on() {
  nmcli --ask con up uuid "$(vpn_id)"
}

function turn_off() {
  nmcli con down uuid "$(vpn_id)"
}

function swap() {
  if is_active Work; then
    NAME=Work turn_off && sleep 3
    NAME=Proton turn_on
  elif is_active Proton; then
    NAME=Proton turn_off && sleep 3
    NAME=Work turn_on
  else
    echo "No connections active."
  fi
}

case $CMD in
  on|up)
    if is_active; then
      echo "Already on"
    else
      turn_on
    fi
    ;;

  off|down)
    if is_active; then
      turn_off
    else
      echo "Already off"
    fi
    ;;

  status)
    if [[ -z ${NAME} ]]; then
      nmcli con |head -n1; nmcli con |grep vpn
      exit
    fi

    if is_active; then
      echo "on"
    else
      echo "off"
    fi
    ;;

  swap)
    swap
    ;;

  *)
    echo "Arguments must be on, up, off or down"
    exit 1
    ;;
esac
