#!/bin/bash

CMD=$1
NAME=$2

if [[ -z $NAME ]]; then
  echo "Must pick configured connection."
  echo -e "Options are:\n"
  nmcli con |grep vpn |awk '{print $1}'
  exit 1
fi

if ! nmcli con |grep -q $NAME; then
  echo "Cannot find VPN configured called \"${NAME}\""
  echo "Please set this up before using!"
  exit 1
fi

is_active() {
  status=$(nmcli con |grep ${NAME} | awk '{print $4}')

  if [[ $status != "--" ]]; then
    true
  else
    false
  fi
}

function vpn_id() {
  nmcli con |grep ${NAME} | awk '{print $2}'
}

case $CMD in
  on|up)
    if is_active; then
      echo "${NAME} VPN connection already active"
    else
      nmcli --ask con up uuid "$(vpn_id)"
    fi

    ;;
  off|down)
    if ! is_active; then
      echo "${NAME} VPN connection already deactivated"
    else
      nmcli con down uuid "$(vpn_id)"
    fi

    ;;

  status)
    if is_active; then
      echo "Active"
    else
      echo "Deactivated"
    fi
    ;;
  *)
    echo "Arguments must be on, up, off or down"
    exit 1
    ;;
esac
